### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Johnnie390** [pipcet/pearl#9]
Hello Pipcet,

you state "We distribute two Mach-O files.."

I see only one **pearl.macho** however..

Ideas?

Regards,

Ry

**Comment by Johnnie390** [comment]
Anyone with ideas?

Regards

Ry

**Comment by pipcet** [comment]
I'm afraid the current version does indeed not include the debian/debootstrap.macho. You can go back and try an older release that has it, if you want to do that:
https://github.com/pipcet/pearl/releases/tag/2021-06-12 still does.

Any help in getting debootstrap back to building would be very appreciated, but I'll try to get to it, too.

Thanks again
Pip

**Comment by pipcet** [comment]
I'm closing this as the pearl-debian.macho image we now once again ship works on at least some machines. Thanks for the report!
